# Loon 基础配置（供 Subconverter loon_rule_base 使用）
# Subconverter 会在此基础上注入 Remote Proxy、Proxy Group、Remote Rule、Plugin

[General]
ipv6-vif = auto
ip-mode = auto
ipv6 = true
dns-server = system,223.5.5.5,119.29.29.29,8.8.8.8,1.1.1.1
disable-udp-ports = 443
wifi-access-http-port = 7222
wifi-access-socks5-port = 7221
allow-wifi-access = true
test-timeout = 2
interface-mode = auto
sni-sniffing = true
disable-stun = false
fast-switch = false
disconnect-on-policy-change = false
switch-node-after-failure-times = 3
internet-test-url = http://connectivitycheck.platform.hicloud.com/generate_204
proxy-test-url = http://www.gstatic.com/generate_204
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,e.crashlynatics.com
bypass-tun = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32
ssid-trigger = "default":rule,"cellular":rule
geoip-url = https://raw.githubusercontent.com/Masaiki/GeoIP2-CN/release/Country.mmdb
ipasn-url = https://raw.githubusercontent.com/P3TERX/GeoLite.mmdb/download/GeoLite2-ASN.mmdb
resource-parser = https://gitlab.com/sub-store/Sub-Store/-/releases/permalink/latest/downloads/sub-store-parser.loon.min.js

[Proxy]

[Remote Proxy]

[Remote Filter]

[Proxy Group]

[Rule]
FINAL,FINAL

[Remote Rule]

[Plugin]

[MITM]
skip-server-cert-verify = false
